# Uncomment the next line to define a global platform for your project
 platform :ios, '11.3'

target 'Movalid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movalid

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Alamofire'

  target 'MovalidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovalidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
