# Uncomment the next line to define a global platform for your project
 platform :ios, '12'

target 'Movalid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Movalid

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Alamofire'
 pod 'XCDYouTubeKit', '~> 2.7'


  target 'MovalidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovalidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
